//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color PreviewFrameColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviewFrameColor"]));
            }
            set {
                this["PreviewFrameColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public byte PreviewShadowAlpha {
            get {
                return ((byte)(this["PreviewShadowAlpha"]));
            }
            set {
                this["PreviewShadowAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PreviewShadowColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviewShadowColor"]));
            }
            set {
                this["PreviewShadowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1920x1080 Computer Mannagement,984x706</string>
  <string>1920x1080 DeviceManager,779x570</string>
  <string>1920x1080 Edge,928x1050</string>
  <string>1920x1080 Explorer,1125x634</string>
  <string>1920x1080 Local Group Policies,752x528</string>
  <string>1920x1080 Registry Editor,1424x758</string>
  <string>1920x1080 Settings,1200x932</string>
  <string>1920x1080 Task Manager,664x591</string>
  <string>1920x1080 Visual Studio 2022,1716x929</string>
  <string>1920x1080 Windows Media Player,1520x855</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Sizes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Sizes"]));
            }
            set {
                this["Sizes"] = value;
            }
        }
    }
}
